import ctypes

user32 = ctypes.windll.user32
SCREEN_WIDTH = user32.GetSystemMetrics(78)
SCREEN_HEIGHT = user32.GetSystemMetrics(79)
WIDTH_BUFFER = .5*SCREEN_WIDTH
HEIGHT_BUFFER = 2*SCREEN_HEIGHT
SCREEN_WIDTH_RANGE = (SCREEN_WIDTH + WIDTH_BUFFER, 0)
SCREEN_HEIGHT_RANGE = (SCREEN_HEIGHT, -HEIGHT_BUFFER)
